@startuml casosusoDOLCA
left to right direction

actor "Usuario" as est 
actor "Administrador" as admin

rectangle "Sistema de Pedidos" {
    usecase "Iniciar sesión" as UC1
    usecase "Realizar pedido" as UC2
}

est --> UC1
est --> UC2
admin --> UC1
admin --> UC2

@enduml
